"""
Django settings for postgram project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   #DONDE ESTA CORRIENDO EL PROYECTO


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%e8!g0^4c@s+grq@-0$dau$by^m+_y_lol%-b&k$hkx2-a9-n$' #HASHING DE LAS CONTRASENAS Y SESIONES QUE SE ALMACENA EN BASE DATOS

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #TRUE SIGNIFICA QUE PROYECTO ESTA EN DESARROLLO

ALLOWED_HOSTS = [] #QUE HOST ESTAN PERMITIDOS INTEERACTUAR EN EL PROYECTO


# CONECTATAR CON LA APP.PY DEL FOLDER DE LA APP

INSTALLED_APPS = [
    #Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Local apps
    'posts',
    'users',
]

#Se encarga de las sesiones de un ususario
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #Creado para que Profiles sin foto y biografia, lo completen antes de continuar.
    'postgram.middleware.ProfileCompletionMiddleware',
]

ROOT_URLCONF = 'postgram.urls' #MODULO DE ENTRADA A URL

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates') #PARA REDIRECCIONAR TEMPLATES A UNA CARPETA COMUN DENTRO DE EL FOLDDER postgram/TEMPLATES/
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'postgram.wsgi.application' #ARCHIVO DE ENTRADA QUE CREO POR DEFAULT STARPROJECT


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
#ARCHIVOS STATICOS PARA DARLE FORMA A IMAGENES O AUDIOS. COMUNMENTE CSS O JS.
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

#para mostrar imagenes
#ver urls.py##
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
##############


LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/' #Para que luego del login nos envíe a posts:feed. Ver doc en AUTH Django.
LOGOUT_REDIRECT_URL = LOGIN_URL #Para que luego del login nos envíe a users:login. Ver doc en AUTH Django.